Module7 task3
htmlacademy-react/839417-what-to-watch-8 pull request #12
Opened 2021-11-08 11:42 UTC by Dimahtml

2021-11-08 19:47 UTC, bini1988 requested changes
> Когда пользователь переходит на страницу с детальной информацией о фильме (/films/:id), с сервера должна быть запрошена информация только по этому фильму.

Надо избавиться от лишнего запроса всех фильмов при захоеде на страницу фильма напрямую.

> Предусмотрите ситуацию, когда пользователь пытается получить информацию о несуществующем фильме. В этом случае пользователь перенаправляется на страницу «404». Дизайн страницы остаётся на ваше усмотрение.

Нужно перенаправлять на страницу 404 если данного фильма не существует

Нужно доработать форму отзыва согласно ТЗ

> Текст отзыва должен быть не меньше 50 и не больше 400 символов.

> Пока пользователь не поставил оценку и не ввел допустимый объём текста, кнопка отправки отзыва не активна.

> При нажатии кнопки «Post» и отправке данных кнопка «Submit» и вся форма должны блокироваться. Разблокировка формы и кнопки происходит в случае успешной отправки или при возникновении ошибки.

> В случае успешной отправки формы пользователь перенаправляется в карточку текущего фильма.

> В случае возникновения ошибки следует уведомить пользователя. Способ отображения ошибки остаётся на усмотрение разработчика.

2021-11-08 19:47 UTC, bini1988 commented on project/src/components/movie-screen/movie-screen.tsx
> +  }, [fetchReviews, id]);
Эти useEffect можно объеденить в один общий

2021-11-08 19:47 UTC, bini1988 commented on project/src/components/review-form/review-form.tsx
>    // eslint-disable-next-line @typescript-eslint/no-unused-vars
Пора убрать этот dsable?

2021-11-08 19:47 UTC, bini1988 commented on project/src/components/similar-films-list/similar-films-list.tsx
> +  let similarFilms = films.filter((film) => film.id !== currentFilm.id);
По идее в возвращаемом сервером списке похожих фильмов не должно быть текущего фильма или это не так?

2021-11-08 19:47 UTC, bini1988 commented on project/src/components/tab-content/tab-content.tsx
>    const starsString = film.starring.slice(0, 3).join(', ');
А почему список актеров обрезан до 3х?

2021-11-08 19:47 UTC, bini1988 commented on project/src/components/tabs/tabs.tsx
> +                }}
Можно просто to={`/films/${filmId}`}

2021-11-08 19:47 UTC, bini1988 commented on project/src/store/api-actions.ts
> +    const {data} = await api.get<BackendFilm[]>(APIRoute.SimilarFilms.replace(':id', id.toString()));
`APIRoute.SimilarFilms.replace(':id', id.toString())` выглядит довольно переусложненным, почему просто не записать `/films/${id}/similar`? Для чего в целом здесь и далее выносить api в константы если они нигде больше не используются?

2021-11-10 09:59 UTC, Dimahtml commented on project/src/components/tab-content/tab-content.tsx
>    const starsString = film.starring.slice(0, 3).join(', ');
На одной вкладке 3 актера and others. На другой вкладке все актеры

2021-11-10 10:00 UTC, Dimahtml commented on project/src/components/similar-films-list/similar-films-list.tsx
> +  let similarFilms = films.filter((film) => film.id !== currentFilm.id);
сам фильм тоже приходит в списке похожих на него

2021-11-10 10:09 UTC, Dimahtml commented on project/src/components/tab-content/tab-content.tsx
>    const starsString = film.starring.slice(0, 3).join(', ');
Ну так должно быть судя по разметке, так у меня было в моках. По факту на сервере в каждом фильме всего 3 актера

2021-11-13 19:02 UTC, bini1988 approved these changes
Хорошая работа над ошибками!

2021-11-13 19:02 UTC, bini1988 commented on project/src/index.tsx
> +// (store.dispatch as ThunkAppDispatch)(fetchPromoFilmAction());
Закоментированный код нужно будет удалить

2021-11-13 19:02 UTC, merged